# -*- coding: utf-8 -*-
"""COVID-19-Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IXBHtqRy3TuGbNLpah4Y6Se58A1lPtBD

###COVID 19
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Covid 19/Covid_19_Clean_Complete.csv')

df.head()

df.shape

df.rename(columns={'Province/State':'state',
           'Country/Region':'country'}, inplace = True)

df.head()

df['Date'].max()

df[df['Date']=='2020-07-27']

top = df[df['Date']=='2020-07-27']

top.head()

top.groupby(by='country')[['Confirmed','Deaths','Recovered','Active']].sum().reset_index()

confirmed = df.groupby(by='Date')['Confirmed'].sum().reset_index()

confirmed

sns.lineplot(data=confirmed, x='Date', y='Confirmed')
plt.show()

plt.figure(figsize=(40,10))
sns.pointplot(data=confirmed, x='Date', y='Confirmed')
plt.xticks(rotation=90)
plt.show()

"""##TOP 10 countries with the most recovered cases"""

top_10_recovered = df.groupby(by='country')['Recovered'].sum().sort_values(ascending = False).head(10).reset_index()

top_10_recovered

sns.barplot(data = top_10_recovered, x = 'country', y='Recovered')
plt.title('Top 10 countries with recovered cases')
plt.show()

"""##Top 10 countries with deaths"""

top_10_deaths = df.groupby(by='country')['Deaths'].sum().sort_values(ascending = False).head(10).reset_index()

top_10_deaths

plt.figure(figsize = (12,10))
sns.barplot(data = top_10_deaths, x = 'country', y = 'Deaths')
plt.title('Top 10 countries with most deaths')
plt.show()

"""##Top 10 countries with most active cases"""

top_10_active = df.groupby(by='country')['Active'].sum().sort_values(ascending = False).head(10).reset_index()

top_10_active

plt.figure(figsize = (12,10))
sns.barplot(data = top_10_active, x = 'country', y = 'Active')
plt.title('Top 10 countries with most deaths')
plt.show()

"""##Country based analysis"""

us = df[df['country'] == 'US']

us

us = us.groupby(by='Date')[['Confirmed','Deaths','Recovered','Active']].sum().reset_index()

us

china = df[df['country'] == 'China']

china = china.groupby(by='Date')[['Confirmed','Deaths','Recovered','Active']].sum().reset_index()

china

india = df[df['country']=='India']

india = india.groupby(by='Date')[['Confirmed','Deaths','Recovered','Active']].sum().reset_index()

india

"""## Compare these countries on the basis of death cases"""

plt.figure(figsize=(40,10))

sns.pointplot(x=us.index, y = us.Deaths, color = 'Red')
sns.pointplot(x=china.index, y=china.Deaths, color = 'Blue')
sns.pointplot(x=india.index, y=india.Deaths, color = 'Green')

plt.xlabel('No. of Days', fontsize = 20)
plt.ylabel('No. of Deaths', fontsize = 20)

### Compare countries on the basis of recovered

plt.figure(figsize=(40,10))

sns.pointplot(x=us.index, y = us.Recovered, color = 'Red')
sns.pointplot(x=china.index, y=china.Recovered, color = 'Blue')
sns.pointplot(x=india.index, y=india.Recovered, color = 'Green')

plt.xlabel('No. of Days', fontsize = 20)
plt.ylabel('No. of Recovered', fontsize = 20)

### Compare countries on the basis of Confirmed

plt.figure(figsize=(40,10))

sns.pointplot(x=us.index, y = us.Confirmed, color = 'Red')
sns.pointplot(x=china.index, y=china.Confirmed, color = 'Blue')
sns.pointplot(x=india.index, y=india.Confirmed, color = 'Green')

plt.xlabel('No. of Days', fontsize = 20)
plt.ylabel('No. of Confirmed', fontsize = 20)

"""# Model Building"""

!pip install prophet

df = pd.read_csv('/content/drive/MyDrive/Covid 19/Covid_19_Clean_Complete.csv', parse_dates=['Date'])

df.head()

df.info()

confirmed = df.groupby(by='Date').sum()['Confirmed'].reset_index()

confirmed

deaths = df.groupby(by='Date').sum()['Deaths'].reset_index()

deaths

recovered = df.groupby(by='Date').sum()['Recovered'].reset_index()

recovered

active = df.groupby(by='Date').sum()['Active'].reset_index()

active

"""# Forecasting for confirmed cases"""

confirmed.columns = ['ds','y']

confirmed

from prophet import Prophet

m = Prophet()

m.fit(confirmed)

future = m.make_future_dataframe(periods=7)

future

forecast = m.predict(future)

forecast

forecast[['ds','yhat','yhat_upper','yhat_lower']]

m.plot(forecast)
plt.show()

import plotly
import plotly.express as px

world = df.groupby(by='Country/Region')[['Confirmed','Active','Deaths','Recovered']].sum().reset_index()

world

figure = px.choropleth(world,locations='Country/Region',
                        locationmode = 'country names',
                        color='Active',
                        hover_name='Country/Region', range_color=[1,20000],
                        color_continuous_scale='reds',
                        title='Countries with Active Cases')
figure.show()

